# Generated by Django 5.0.10 on 2025-06-07 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bikes", "0002_initial"),
        ("bookings", "0002_initial"),
        ("ratings", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="rating",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="rating",
            name="booking",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rating",
                to="bookings.booking",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rating",
            unique_together={("bike", "user", "booking")},
        ),
    ]
